backend:
  name: git-gateway
  branch: main
  publish_mode: editorial_workflow
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
collections: 
  - name: "blog"
  label: "Blog"
  folder: "src/blog"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "File", name: "file", widget: "file" 
      media_library: 
        config: 
        multiple: true
        choose_url: true
        }
      - { label: "Author", name: "author", widget: "list", default: ["Chelsea Irish"]}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }